### ISSUE TITLE
use udev instead of compare prev and now state

### ISSUE THREAD

**Issue by amirarsalan** [errbufferoverfl/usb-canary#11]
Hi,
It's better for this project use from udev capability instead compare state.
We can use pydev that monitor all ports in computer. Ex,

```python
import pyudev
context = pyudev.Context()
monitor = pyudev.Monitor.from_netlink(context)
monitor.filter_by('block')
def log_event(action, device):
    if 'ID_FS_TYPE' in device:
        print('{0} - {1}'.format(action, device.get('ID_FS_LABEL'))

observer = pyudev.MonitorObserver(monitor, log_event)
observer.start()
# when connect a device print below messsage, Ex
# add - Hard1
```
by above example, when connected or disconnect a device to computer run log_event function and can run any action!

**Comment by errbufferoverfl** [comment]
Hi thanks for submitting.

Since version 2.x.x was released we have moved to using `psutil` instead of `pyudev` as the package used for monitoring devices. Unfortunately while `pyudev` was great it did not support OSX.

Moving to a system agnostic package allows us to keep the code base more consistent and easier to maintain now and in the future as we rely on less packages to ensure USB Canary works across different operating systems.

If you are using version 1.x.x we encourage you to upgrade to version 2.0.1 as anything on the version 1.x.x branch will no longer be maintained.
