### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by ghost** [errbufferoverfl/usb-canary#3]
What will it be...?

usbcanary.exe
--install --- install as service and start it
--uninstall --- remove service
--config X:/y/z.config --- pick other config file(if not set, read ./usbcanary.config file)

usbcanary.config
UseWebAPI false
UseHTTPProxy 1.2.3.4:5
PlaySoundOnDetect true
Soundfile X:/y/z/p.mp3
RunCommandOnDetect true
RunCommand "shutdown -s -t 0"

**Comment by errbufferoverfl** [comment]
Hi yoursoftwarebug,

At the moment I am still investigating how USB Canary can be ported to Windows, ideally I am looking into making it a service of some kind but I'm not too sure yet sorry, once I've worked out some more details I'm happy to keep you updated.

**Comment by prameshbajra** [comment]
So any new updates on this?

**Comment by errbufferoverfl** [comment]
@Suzal3579 unfortunately not, I am currently working on the Mac version as it requires less work to get going than the Windows version and refactoring the code base to potentially add blocking and whitelisting.

Because this is a spare time project, between work and life I haven't had as much time as I would like to work on this.

Edit: I also currently don't have internet at my current residence so development/testing has been difficult relying solely on mobile data.

**Comment by errbufferoverfl** [comment]
🎉 **ANNOUNCEMENT** 🎉 
So after a bit of research, finding a WIndows Service Python recipe and trying out Daemoniker I have concluded that at this point in time I am not able to support Windows at this time.

I dislike having to just say no because the feature request is so resonable and I did mention that I would be porting it to Windows and OSX, **HOWEVER** as I just mentioned at this point of time I have been unable to find a workable way to make version 2.0 work on Windows.

I have had a number of problems making the app cross platform, and so wether this all means that I make a fork of this just for Windows I'm not too sure yet. 

I originally wrote this for Linux as that was the primary platform I worked on and the platform I knew best.

If there are Python/Windows developers who think they can help please feel free to either comment on this issue, or get in contact with me, for now I am closing this issue, but may open it in the near future.

Thanks for your support.
