### ISSUE TITLE
macOS support.

### ISSUE THREAD

**Issue by ghost** [errbufferoverfl/usb-canary#7]
I noticed that you are planning on making OS X support. I've been using [https://github.com/hephaest0s/usbkill](url) this, maybe help you with some ideas. Cheers.

**Comment by errbufferoverfl** [comment]
Hey @sogseal thanks for sharing this! I will definitely take a look and see how they support OSX!

**Comment by errbufferoverfl** [comment]
🎉  **ANNOUNCEMENT** 🎉  
As people following this issue, may or may not have seen, recently I have been incredibly busy with things outside of maintaining an OS (open source) tool. However, with that said I have recently decided that for now I will not be supporting Windows.

However with that said, I have been doing a fair bit of refactoring to make the code base a little shinier, version 2 is in the works and OSX support is much easier for me to support as it is closer to Linux than OSX is.

I am currently looking into switching the daemon manager that I originally used and have already implemented the USB monitoring using Quartz. Once I have the daemon side of things sorted out, I will potentially release an alpha or beta of some sort.

**Comment by errbufferoverfl** [comment]
🎉 **UPDATE** 🎉 
Hey guys! I have found a bug that affects the **new** Linux and OSX implementation - this bug isn't in the current code base but rather the working copy I have locally.

The bug is basically your standard race condition, if you plug in and remove a USB fast enough you can plug the device in without being detected which as you can imagine is a pretty big deal. 

I'm currently doing some research on a fix to this and have investigating different libraries that won't have this problem. Being a one man show getting OSX support has been a slow process so I apologise for the delays!

**Comment by errbufferoverfl** [comment]
🎉 **ANNOUNCEMENT** 🎉 

Version 2.0.0 has been released! It now supports OSX! Woooooo!
